[package]
name = "analysis"
edition.workspace = true
version.workspace = true

[dependencies]
control = { path = "../control" }
rustfft = { workspace = true }
anyhow = { workspace = true }
ort = { workspace = true }
ort-sys = { workspace = true }
ndarray = { workspace = true }

[dev-dependencies]
decode = { path = "../decode" }
